### ISSUE TITLE
Extend aliases with stylized values

### ISSUE THREAD

**Issue by Jokero** [dolsem/eslint-plugin-filename-rules#1]
```js
const aliases = {
    PascalCase: ...,
    camelCase: ...,
    snake_case: ...,
    'kebab-case': ...
};
```
So it will be possible to write as follows:
```js
rules: {
    // for other users it will be more obvious what snake_case actually means
    'filename-rules/match': [2, 'snake_case'],
```

**Comment by dolsem** [comment]
Yeah that's an interesting idea. I'd like to keep default aliases, but would be nice to also these stylized options as well. Would you like to submit a PR?

**Comment by Jokero** [comment]
@dolsem Yeah, will do

**Comment by Jokero** [comment]
@dolsem Could you please release a new version?

**Comment by dolsem** [comment]
@Jokero done
