### ISSUE TITLE
ignore option?

### ISSUE THREAD

**Issue by ash-r1** [dolsem/eslint-plugin-filename-rules#2]
I want to use it with pascalcase optioin, but I have to ignore some files, e.g. `.eslintrc.js` or `rollup.config.js` etc...

How about ignoring option?

**Comment by dolsem** [comment]
If you want to skip linting those files entirely you can add them to `.eslintignore`. If you want to just disable this rule only, you can do it the usual way by adding /* eslint-disable filename-rules/match */ at the top of the file. Let me know if that solves your problem.

**Comment by ash-r1** [comment]
I want to keep other linting rules for these files.

> /* eslint-disable filename-rules/match */ at the top of the file.

wow, thanks. It solves the problem.

**Comment by Tzahile** [comment]
I wanted to ignore all `index.js` files (maybe there's an option that supports it?) after matching all to PascalCase.
In this case, I added an override rule:
```js
'overrides': [
    {
      'files': ['**/index.vue'],
      'rules': {
        'filename-rules/match': [0]
      }
    }
]
```
